# karsajobs service
apiVersion: v1
kind: Service
metadata:
  name: karsajobs-service
# spec untuk menentukan spesifikasi service
spec:
  selector:
    app: karsajobs
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
