# karsajobs service
apiVersion: v1
kind: Service
metadata:
  name: karsajobs-service
  namespace: tugas2
  labels:
    app: karsajobs
    type: backend
# spec untuk menentukan spesifikasi service
spec:
  selector:
    type: backend
  ports:
    - port: 8080
  type: NodePort
