# mongo pv-pvc (Persistent Volume - Persistent Volume Claim)
apiVersion: v1
# menggunakan kind: PersistentVolumeClaim
kind: PersistentVolume
# metadata untuk menamakan persistent volume
metadata:
  name: mongo-pv-volume
  labels:
    type: local
    app: mongo
  namespace: tugas2
# spec untuk menentukan spesifikasi persistent volume
spec:
  # menggunakan stroageClassName: hostpath (windows)
#  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp"
---
# PVC (Persistent Volume Claim) untuk mongo
apiVersion: v1
# menggunakan kind: PersistentVolumeClaim
kind: PersistentVolumeClaim
# metadata untuk menamakan persistent volume claim
metadata:
  name: mongo-pv-claim
  labels:
    app: mongo
  namespace: tugas2
# spec untuk menentukan spesifikasi persistent volume claim
spec:
#  storageClassName: manual
  resources:
    requests:
      storage: 500Mi
  accessModes:
    - ReadWriteOnce
#  volumeName: mongo-pv-volume # Menambahkan referensi ke PersistentVolume yang sudah didefinisikan    
# perintah untuk menjalankan persistent volume claim dengan namespace default
# kubectl apply -f mongodb/mongo-pv-pvc.yml    
