# Menggunakan apiVersion: v1
apiVersion: v1
# Menggunakan kind: Service
kind: Service
# metadata untuk menamakan service
metadata:
  name: mongo-service
  namespace: tugas2
  labels:
    app: mongo-service
    type: mongodb
# spec untuk menentukan spesifikasi service
spec:
  ports:
    - port: 27017
  clusterIP: None
  selector:
    type: mongodb

# perintah untuk menjalankan service dengan namespace default
# kubectl apply -f mongodb/mongo-service.yml
