# mongo secret:
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # admin username root di encode menggunakan base64
  MONGO_ROOT_USERNAME: YWRtaW4=
  # passwrod supersecretpassword di encode menggunakan base64
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==

# perintah untuk menjalankan secret dengan namespace default
# kubectl apply -f mongodb/mongo-secret.yml